logging:
  level: INFO
  loggers:
    com.miniqueue: DEBUG
# Database settings.
database:

    # the name of the JDBC driver, mysql in our case

    driverClass: com.mysql.jdbc.Driver

    # the username

    user: sam

    # the password

    password: password

    # the JDBC URL; the database is called DWGettingStarted

    url: jdbc:mysql://localhost:3306/miniq

logging:
  level: INFO
  loggers:
    org.skife.jdbi.v2: TRACE